### ISSUE TITLE
1 exception(s): Exception #0 (Exception): Warning: Cannot modify header information - headers already sent by

### ISSUE THREAD

**Issue by rhyswoos** [mageplaza/magento-2-security#2]
I'm getting the following error after installing

1 exception(s): Exception #0 (Exception): Warning: Cannot modify header information - headers already sent by ...

**Comment by rhyswoos** [comment]
``1 exception(s): Exception #0 (Exception): Warning: Cannot modify header information - headers already sent by (output started at /home/duckandt/public_html/lib/internal/Mageplaza/Security/browser-detector/registration.php:1) in /home/duckandt/public_html/vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php on line 148 Exception #0 (Exception): Warning: Cannot modify header information - headers already sent by (output started at /home/duckandt/public_html/lib/internal/Mageplaza/Security/browser-detector/registration.php:1) in /home/duckandt/public_html/vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php on line 148 #0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'Cannot modify h...', '/home/duckandt/...', 148, Array) #1 /home/duckandt/public_html/vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php(148): setcookie('form_key', 'CA9JC9huZalNeVP...', 1552128264, '/', 'duckandtrowel.c...', false, false) #2 /home/duckandt/public_html/vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php(121): Magento\Framework\Stdlib\Cookie\PhpCookieManager->setCookie('form_key', 'CA9JC9huZalNeVP...', Array) #3 /home/duckandt/public_html/vendor/magento/framework/App/PageCache/FormKey.php(76): Magento\Framework\Stdlib\Cookie\PhpCookieManager->setPublicCookie('form_key', 'CA9JC9huZalNeVP...', Object(Magento\Framework\Stdlib\Cookie\PublicCookieMetadata)) #4 /home/duckandt/public_html/vendor/magento/module-page-cache/Plugin/RegisterFormKeyFromCookie.php(104): Magento\Framework\App\PageCache\FormKey->set('CA9JC9huZalNeVP...', Object(Magento\Framework\Stdlib\Cookie\PublicCookieMetadata)) #5 /home/duckandt/public_html/vendor/magento/module-page-cache/Plugin/RegisterFormKeyFromCookie.php(79): Magento\PageCache\Plugin\RegisterFormKeyFromCookie->updateCookieFormKey('CA9JC9huZalNeVP...') #6 /home/duckandt/public_html/vendor/magento/framework/Interception/Interceptor.php(121): Magento\PageCache\Plugin\RegisterFormKeyFromCookie->beforeDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Magento\Framework\App\Request\Http)) #7 /home/duckandt/public_html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #8 /home/duckandt/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http)) #9 /home/duckandt/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #10 /home/duckandt/public_html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array) #11 /home/duckandt/public_html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http)) #12 /home/duckandt/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch() #13 /home/duckandt/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor)) #14 {main}``

**Comment by rhyswoos** [comment]
FYI Resolved this File lib/internal/Mageplaza/Security/browser-detector/registration.php has white space before the opening php line

**Comment by thaimageplaza** [comment]
Hi,
It's great that you've solved your problem and shared it with the community.
Thank you for that.
And because the issue is resolved we will close the issue.
Thank you again!

**Comment by KnK123** [comment]
Hi @thaimageplaza 

could you please advise how to fix this error.

{"0":"Warning: Cannot modify header information - headers already sent by (output started at \/srv\/public_html\/vendor\/magento\/framework\/Mail\/Template\/TransportBuilder.php:218) in \/srv\/public_html\/vendor\/magento\/framework\/Stdlib\/Cookie\/PhpCookieManager.php on line 148","1":"<pre>#1 setcookie() called at [vendor\/magento\/framework\/Stdlib\/Cookie\/PhpCookieManager.php:148]

M2 version is: Magento/2.3 (Community)

Thanks
