### ISSUE TITLE
fail to get respond

### ISSUE THREAD

**Issue by samcheunghc** [mageplaza/magento-2-security#3]
Below msg showed after I download and install security module:
Failed to load resource: the server responded with a status of 403 (Forbidden)
And I have already try refresh the blacklist and whitelist.

**Comment by thaimageplaza** [comment]
Hi,
I’m not sure that I can understand your issue/question, 
so could you please explain your problem in more details/ steps by steps to replicate the problem and send me some screenshots?
I really hope for your cooperation. Thank you!

**Comment by samcheunghc** [comment]
Hi,

I cannot entry the website after I download and install the security extension.
The console have a msg of “GET https://www.three.com.hk:10043/favicon.ico 403 (Forbidden)”
“<p>You don't have permission to access /favicon.ico”

The msg still here after I reset the blacklist, whitelist and disable the module.
Thanks!
[cid:image001.png@01D5118B.BF498350]
[cid:image002.png@01D5118B.BF498350]

**Comment by thaimageplaza** [comment]
Please list the steps when you install the extension?
I need to confirm that you installed it correctly.
Thank you!

**Comment by samcheunghc** [comment]
Download the file
Put the file “Security” to app/code/Mageplaza
[cid:image001.png@01D5118F.6E7785E0]
And put the file “Mageplaza” to internal
[cid:image002.png@01D5118F.6E7785E0]

Then Setup upgrade and clean cache

Thanks!

**Comment by thaimageplaza** [comment]
I think you have installed a lack of support library of security extension.
Please install more 'sinergi/browser-detector' library.
And check again. Thank you!

**Comment by samcheunghc** [comment]
Where can I download more ‘sinergi/browser-detector’ library?
Thanks!

**Comment by samcheunghc** [comment]
Where should the library place to.

**Comment by samcheunghc** [comment]
I have install the sinergi library in app/code
But the problem still happen.
Thanks!

**Comment by thaimageplaza** [comment]
Hi,
you can install the library via composer with the command line:
composer require sinergi/browser-detector
Please check again. Thank you!
