### ISSUE TITLE
Won't activate

### ISSUE THREAD

**Issue by killday** [mageplaza/magento-2-security#7]
Hi,
When I click on Activate Now nothing happens. 
system.log:  Too late for the schedule Schedule Id: 2564074 Job Code: mageplaza_security_send_mail

Magento 2.2.0
Security 1.1.4

**Comment by NgoDuVietHung97** [comment]
Hi @killday,

To solve this problem, please download and replace the attached file following path:
 - Activate.php: Mageplaza/Core/Model/Activate.php

[Activate.zip](https://github.com/mageplaza/magento-2-security/files/3558748/Activate.zip)

Then, please try to activate the extension again and let me know the result.
Thanks!

**Comment by killday** [comment]
Hi @NgoDuVietHung97 ,

Thanks that did the job.
