### ISSUE TITLE
IPv6 supported?

### ISSUE THREAD

**Issue by DanielRuf** [mageplaza/magento-2-security#9]
The code for cechking and comparing IPs seems to use / expect IPv4 addresses.
Is IPv6 supported and where can we find the relevant tests?

**Comment by Shinichi69** [comment]
Hi @DanielRuf 

Unfortunately, the current version has not supported this function yet.
I'm so sorry about that. However, I will surely note it to consider developing it in the future so please look forward to this. 

Thank you very much for your feedback.

**Comment by Shinichi69** [comment]
Closed due no response within 7 days.

**Comment by DanielRuf** [comment]
> Closed due no response within 7 days.

That is a weird response to your own last response ;-)

Why not keep it open to have it in your backlog?
